name: parque
description: Aplicativo de gerenciamento de parques de São Luís - MA
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  intl: ^0.19.0
  lottie: ^3.1.2
  google_maps_flutter: ^2.9.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  provider: ^6.0.5
  # geolocator: ^13.0.2
  # permission_handler: ^11.3.1
  # path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash_bg.png
    - assets/images/itapiraco.png
    - assets/icons/Map.svg
    - assets/icons/Calendar_Check.svg
    - assets/icons/calendar.svg
    - assets/icons/info.svg
    - assets/images/RANGEDOR.png
    - assets/images/danca.png
    - assets/images/trilha.png
    - assets/images/borboletario.png
    - assets/lottie/heart.json
    - assets/images/onboarding1.svg
    - assets/images/onboarding2.svg
    - assets/images/onboarding3.svg
    - assets/images/onboarding4.svg
    - assets/images/success.svg
    
flutter_native_splash:
  background_image: assets/images/splash_bg.png
  ios: true
  android: true
  android_12:
    background_image: assets/images/splash_bg.png
