-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSThklSyuexUosm/O
Qjp0Vt5qcoZAQleS94YAFDx7nrCgCgYIKoZIzj0DAQehRANCAATOtR1GGhXaMm1Z
Ozso4waIETP2I55yqBWVuCUQMXYwXnWVUoVWebAMuEqkD5HT5o4WUk1kayPPmhoV
jcFLtn4F
-----END PRIVATE KEY-----